### ISSUE TITLE
Description of Linux Implementation is Wrong

### ISSUE THREAD

**Issue by SvenTo** [priyankchheda/chrome_password_grabber#1]
Hi,
the following description of the Linux implementation is not true:
> on Linux:
> password is peanuts

The implementation depends on the used password store (option: ``--password-store=<basic|gnome|kwallet>``). The password is *peanuts* only if the basic store is used. In default, it detects automatically if KWallet or Gnome keyring is available and storing a random password there.

**Comment by cronzevid** [comment]
This is absolutely true. I've also tried working on similar topic, but couldn't achieve any success.
Though there is a pretty straightforward [explanation](https://stackoverflow.com/questions/23153159/decrypting-chromium-cookies/23727331) on how to do this, I wasn't able to implement it.

**Comment by priyankchheda** [comment]
https://github.com/priyankchheda/chrome_password_grabber/commit/b37daccb6b7c99705444ce8f8870d0971e7aac9f

This commit should fix the issue. Please verify.
