### ISSUE TITLE
Standalone use chrome_password_grabber.py ?

### ISSUE THREAD

**Issue by Baltazar500** [priyankchheda/chrome_password_grabber#12]
Hi.

How to standalone use chrome_password_grabber.py ?

I've never used python, and I don't know how to use this code. Is it possible to pass the path to the database to the script 

>chrome_password_grabber.py ./Login\ Data

and get the passwords at the output ?

**Comment by priyankchheda** [comment]
No. You can't pass the path to the database to the script. Depending in your operating system, dbpath variable will set.
Please read the usage in README.md file.
