### ISSUE TITLE
Help me !

### ISSUE THREAD

**Issue by rasothecoder** [priyankchheda/chrome_password_grabber#13]
1.-) Im new at python and i don't know how to run this project. 
2.-) Please tell me process i have to do.
3.-) I have Login Data file its possible for grabbing passwords?

**Comment by zim0101** [comment]
1. Learn the basics of python syntax and OOP. You will get to know how to run python
2. No 1 will solve this one
3. Yes possible

**Comment by priyankchheda** [comment]
please read the usage in README.md file
