### ISSUE TITLE
Outdated README file?

### ISSUE THREAD

**Issue by littlesandra88** [priyankchheda/chrome_password_grabber#15]
The first line of how to use says
```
>>> from chrome_passwd import ChromePasswd
```
by the file is not called `chrome_password`. Changing it gives
```
>>> from chrome import ChromePasswd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ChromePasswd' from 'chrome' (/tmp/chrome_password_grabber/chrome.py)
```
The `.py` file on that repository has no `ChromePasswd` Method or Class.

So there a lot of changes must have happened since the README was last updated?

**Comment by priyankchheda** [comment]
Thank you for pointing that out.
README.md file is now updated.
