### ISSUE TITLE
Decode Error

### ISSUE THREAD

**Issue by yarons** [priyankchheda/chrome_password_grabber#7]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 1: invalid continuation byte

Happened after changing the location to the correct folder.

**Comment by x899** [comment]
please add more information.
Also mention the operating system.

**Comment by yarons** [comment]
Linux, Python 3.7.4 iirc.

**Comment by x899** [comment]
> after changing the location to the correct folder
what changes?

**Comment by yarons** [comment]
Those I reported in the other bug report, from `google-chrome` to `chromium`.

**Comment by ferloopew** [comment]
This may help: https://stackoverflow.com/questions/23153159/decrypting-chromium-cookies/44808566#44808566

**Comment by priyankchheda** [comment]
https://github.com/priyankchheda/chrome_password_grabber/commit/b37daccb6b7c99705444ce8f8870d0971e7aac9f

@yarons this commit should fix the issue. Please verify.

**Comment by yarons** [comment]
Sorry, I don't have access to that machine anymore.

**Comment by faridcher** [comment]
I also get this error:

```py
>>> cc.get_password(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/farid/chrome_password_grabber/chrome.py", line 133, in get_password
    _passwd = self.chrome_os.decrypt_func(result[2])
  File "/home/farid/chrome_password_grabber/chrome.py", line 100, in decrypt_func
    return decrypted.strip().decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 2: invalid start byte
```

The content of `decrypted` is `b'Oy\xf8RZi0\x9a^\xb7\xa7\xb4$\xcd\xb8$'`
